import type { Metadata } from "next";
import { PageLayout } from "@/components/page-layout";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms governing your use of the FlowForge AI website and services.",
};

const UPDATED = "January 2026";

export default function TermsPage() {
  return (
    <PageLayout>
      <article className="container max-w-3xl py-16">
        <h1 className="font-display text-4xl font-semibold tracking-tight">Terms of Service</h1>
        <p className="text-sm text-muted-foreground">Last updated: {UPDATED}</p>

        <p className="mt-6 text-muted-foreground">
          These terms govern your use of the FlowForge AI website and services. By using the site or
          subscribing to a retainer, you agree to them.
        </p>

        <Section title="1. Services">
          <p>
            FlowForge AI provides automation design, build, and monitoring on a monthly retainer.
            Deliverables, timelines, and scope are defined in your engagement. Retainers are month-to-month
            after the initial 30-day onboarding, and you retain ownership of the automations we build in your
            own accounts.
          </p>
        </Section>

        <Section title="2. Payment">
          <p>
            Retainers are billed monthly in advance via Stripe. Failed payments may pause active automations
            until resolved. Fees are non-refundable except where required by law.
          </p>
        </Section>

        <Section title="3. Acceptable use">
          <p>
            You agree not to misuse the site — including attempting to disrupt it, probe it for
            vulnerabilities without authorization, or use the AI features to generate unlawful content.
          </p>
        </Section>

        <Section title="4. AI-generated output">
          <p>
            Automation ideas and audit summaries produced on this site are generated by AI for informational
            purposes and are not a guarantee of specific results. Savings estimates are illustrative.
          </p>
        </Section>

        <Section title="5. Liability">
          <p>
            The site and its content are provided &ldquo;as is&rdquo; without warranties. To the maximum extent
            permitted by law, FlowForge AI is not liable for indirect or consequential damages arising from
            your use of the site.
          </p>
        </Section>

        <Section title="6. Contact">
          <p>
            Questions? Email{" "}
            <a href="mailto:hello@flowforge.ai" className="text-cyan-electric">hello@flowforge.ai</a>.
          </p>
        </Section>
      </article>
    </PageLayout>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="font-display text-xl font-semibold">{title}</h2>
      <div className="mt-2 space-y-3 text-muted-foreground">{children}</div>
    </section>
  );
}
