export type SeoPage = {
  slug: string;
  vertical: string;
  workflow: string;
  h1: string;
  metaTitle: string;
  metaDescription: string;
  problem: string;
  solution: string;
  steps: { label: string; tool: string }[];
  tools: string[];
  savings: string;
};

export const seoPages: SeoPage[] = [
  {
    slug: "restaurant-reservation-and-review-agent",
    vertical: "seo.restaurantReservationAndReviewAgent.vertical",
    workflow: "seo.restaurantReservationAndReviewAgent.workflow",
    h1: "seo.restaurantReservationAndReviewAgent.h1",
    metaTitle: "seo.restaurantReservationAndReviewAgent.metaTitle",
    metaDescription: "seo.restaurantReservationAndReviewAgent.metaDescription",
    problem: "seo.restaurantReservationAndReviewAgent.problem",
    solution: "seo.restaurantReservationAndReviewAgent.solution",
    steps: [
      { label: "seo.restaurantReservationAndReviewAgent.step1", tool: "GPT agent" },
      { label: "seo.restaurantReservationAndReviewAgent.step2", tool: "Calendly" },
      { label: "seo.restaurantReservationAndReviewAgent.step3", tool: "Twilio" },
      { label: "seo.restaurantReservationAndReviewAgent.step4", tool: "Gmail" },
    ],
    tools: ["GPT agent", "Calendly", "Twilio", "Gmail", "Google Reviews"],
    savings: "seo.restaurantReservationAndReviewAgent.savings",
  },
  {
    slug: "shopify-store-abandoned-cart-recovery",
    vertical: "seo.shopifyStoreAbandonedCartRecovery.vertical",
    workflow: "seo.shopifyStoreAbandonedCartRecovery.workflow",
    h1: "seo.shopifyStoreAbandonedCartRecovery.h1",
    metaTitle: "seo.shopifyStoreAbandonedCartRecovery.metaTitle",
    metaDescription: "seo.shopifyStoreAbandonedCartRecovery.metaDescription",
    problem: "seo.shopifyStoreAbandonedCartRecovery.problem",
    solution: "seo.shopifyStoreAbandonedCartRecovery.solution",
    steps: [
      { label: "seo.shopifyStoreAbandonedCartRecovery.step1", tool: "Shopify" },
      { label: "seo.shopifyStoreAbandonedCartRecovery.step2", tool: "GPT agent" },
      { label: "seo.shopifyStoreAbandonedCartRecovery.step3", tool: "Twilio" },
      { label: "seo.shopifyStoreAbandonedCartRecovery.step4", tool: "Sheets" },
    ],
    tools: ["Shopify", "GPT agent", "Twilio", "Gmail", "Sheets"],
    savings: "seo.shopifyStoreAbandonedCartRecovery.savings",
  },
  {
    slug: "plumbing-missed-call-to-booked-job",
    vertical: "seo.plumbingMissedCallToBookedJob.vertical",
    workflow: "seo.plumbingMissedCallToBookedJob.workflow",
    h1: "seo.plumbingMissedCallToBookedJob.h1",
    metaTitle: "seo.plumbingMissedCallToBookedJob.metaTitle",
    metaDescription: "seo.plumbingMissedCallToBookedJob.metaDescription",
    problem: "seo.plumbingMissedCallToBookedJob.problem",
    solution: "seo.plumbingMissedCallToBookedJob.solution",
    steps: [
      { label: "seo.plumbingMissedCallToBookedJob.step1", tool: "Twilio" },
      { label: "seo.plumbingMissedCallToBookedJob.step2", tool: "Twilio" },
      { label: "seo.plumbingMissedCallToBookedJob.step3", tool: "GPT agent" },
      { label: "seo.plumbingMissedCallToBookedJob.step4", tool: "Calendly" },
    ],
    tools: ["Twilio", "GPT agent", "Calendly", "Sheets"],
    savings: "seo.plumbingMissedCallToBookedJob.savings",
  },
  {
    slug: "real-estate-lead-qualification-and-follow-up",
    vertical: "seo.realEstateLeadQualificationAndFollowUp.vertical",
    workflow: "seo.realEstateLeadQualificationAndFollowUp.workflow",
    h1: "seo.realEstateLeadQualificationAndFollowUp.h1",
    metaTitle: "seo.realEstateLeadQualificationAndFollowUp.metaTitle",
    metaDescription: "seo.realEstateLeadQualificationAndFollowUp.metaDescription",
    problem: "seo.realEstateLeadQualificationAndFollowUp.problem",
    solution: "seo.realEstateLeadQualificationAndFollowUp.solution",
    steps: [
      { label: "seo.realEstateLeadQualificationAndFollowUp.step1", tool: "Sheets" },
      { label: "seo.realEstateLeadQualificationAndFollowUp.step2", tool: "GPT agent" },
      { label: "seo.realEstateLeadQualificationAndFollowUp.step3", tool: "Calendly" },
      { label: "seo.realEstateLeadQualificationAndFollowUp.step4", tool: "Gmail" },
    ],
    tools: ["GPT agent", "Calendly", "Gmail", "Twilio", "Sheets"],
    savings: "seo.realEstateLeadQualificationAndFollowUp.savings",
  },
  {
    slug: "dental-practice-appointment-reminders-and-rebooking",
    vertical: "seo.dentalPracticeAppointmentRemindersAndRebooking.vertical",
    workflow: "seo.dentalPracticeAppointmentRemindersAndRebooking.workflow",
    h1: "seo.dentalPracticeAppointmentRemindersAndRebooking.h1",
    metaTitle: "seo.dentalPracticeAppointmentRemindersAndRebooking.metaTitle",
    metaDescription: "seo.dentalPracticeAppointmentRemindersAndRebooking.metaDescription",
    problem: "seo.dentalPracticeAppointmentRemindersAndRebooking.problem",
    solution: "seo.dentalPracticeAppointmentRemindersAndRebooking.solution",
    steps: [
      { label: "seo.dentalPracticeAppointmentRemindersAndRebooking.step1", tool: "Calendly" },
      { label: "seo.dentalPracticeAppointmentRemindersAndRebooking.step2", tool: "Twilio" },
      { label: "seo.dentalPracticeAppointmentRemindersAndRebooking.step3", tool: "GPT agent" },
      { label: "seo.dentalPracticeAppointmentRemindersAndRebooking.step4", tool: "Gmail" },
    ],
    tools: ["Calendly", "Twilio", "GPT agent", "Gmail", "Sheets"],
    savings: "seo.dentalPracticeAppointmentRemindersAndRebooking.savings",
  },
  {
    slug: "consulting-proposal-to-onboarding-autopilot",
    vertical: "seo.consultingProposalToOnboardingAutopilot.vertical",
    workflow: "seo.consultingProposalToOnboardingAutopilot.workflow",
    h1: "seo.consultingProposalToOnboardingAutopilot.h1",
    metaTitle: "seo.consultingProposalToOnboardingAutopilot.metaTitle",
    metaDescription: "seo.consultingProposalToOnboardingAutopilot.metaDescription",
    problem: "seo.consultingProposalToOnboardingAutopilot.problem",
    solution: "seo.consultingProposalToOnboardingAutopilot.solution",
    steps: [
      { label: "seo.consultingProposalToOnboardingAutopilot.step1", tool: "GPT agent" },
      { label: "seo.consultingProposalToOnboardingAutopilot.step2", tool: "Stripe" },
      { label: "seo.consultingProposalToOnboardingAutopilot.step3", tool: "Sheets" },
      { label: "seo.consultingProposalToOnboardingAutopilot.step4", tool: "Calendly" },
    ],
    tools: ["GPT agent", "Stripe", "Calendly", "Gmail", "Sheets"],
    savings: "seo.consultingProposalToOnboardingAutopilot.savings",
  },
  {
    slug: "gym-fitness-membership-onboarding-and-winback",
    vertical: "seo.gymFitnessMembershipOnboardingAndWinback.vertical",
    workflow: "seo.gymFitnessMembershipOnboardingAndWinback.workflow",
    h1: "seo.gymFitnessMembershipOnboardingAndWinback.h1",
    metaTitle: "seo.gymFitnessMembershipOnboardingAndWinback.metaTitle",
    metaDescription: "seo.gymFitnessMembershipOnboardingAndWinback.metaDescription",
    problem: "seo.gymFitnessMembershipOnboardingAndWinback.problem",
    solution: "seo.gymFitnessMembershipOnboardingAndWinback.solution",
    steps: [
      { label: "seo.gymFitnessMembershipOnboardingAndWinback.step1", tool: "Sheets" },
      { label: "seo.gymFitnessMembershipOnboardingAndWinback.step2", tool: "GPT agent" },
      { label: "seo.gymFitnessMembershipOnboardingAndWinback.step3", tool: "Sheets" },
      { label: "seo.gymFitnessMembershipOnboardingAndWinback.step4", tool: "Twilio" },
    ],
    tools: ["GPT agent", "Twilio", "Gmail", "Calendly", "Sheets"],
    savings: "seo.gymFitnessMembershipOnboardingAndWinback.savings",
  },
  {
    slug: "law-firm-intake-and-document-collection",
    vertical: "seo.lawFirmIntakeAndDocumentCollection.vertical",
    workflow: "seo.lawFirmIntakeAndDocumentCollection.workflow",
    h1: "seo.lawFirmIntakeAndDocumentCollection.h1",
    metaTitle: "seo.lawFirmIntakeAndDocumentCollection.metaTitle",
    metaDescription: "seo.lawFirmIntakeAndDocumentCollection.metaDescription",
    problem: "seo.lawFirmIntakeAndDocumentCollection.problem",
    solution: "seo.lawFirmIntakeAndDocumentCollection.solution",
    steps: [
      { label: "seo.lawFirmIntakeAndDocumentCollection.step1", tool: "GPT agent" },
      { label: "seo.lawFirmIntakeAndDocumentCollection.step2", tool: "Sheets" },
      { label: "seo.lawFirmIntakeAndDocumentCollection.step3", tool: "Gmail" },
      { label: "seo.lawFirmIntakeAndDocumentCollection.step4", tool: "Twilio" },
    ],
    tools: ["GPT agent", "Gmail", "Twilio", "Sheets", "Stripe"],
    savings: "seo.lawFirmIntakeAndDocumentCollection.savings",
  },
  {
    slug: "ecommerce-customer-support-inbox-triage",
    vertical: "seo.ecommerceCustomerSupportInboxTriage.vertical",
    workflow: "seo.ecommerceCustomerSupportInboxTriage.workflow",
    h1: "seo.ecommerceCustomerSupportInboxTriage.h1",
    metaTitle: "seo.ecommerceCustomerSupportInboxTriage.metaTitle",
    metaDescription: "seo.ecommerceCustomerSupportInboxTriage.metaDescription",
    problem: "seo.ecommerceCustomerSupportInboxTriage.problem",
    solution: "seo.ecommerceCustomerSupportInboxTriage.solution",
    steps: [
      { label: "seo.ecommerceCustomerSupportInboxTriage.step1", tool: "Gmail" },
      { label: "seo.ecommerceCustomerSupportInboxTriage.step2", tool: "GPT agent" },
      { label: "seo.ecommerceCustomerSupportInboxTriage.step3", tool: "Shopify" },
      { label: "seo.ecommerceCustomerSupportInboxTriage.step4", tool: "Sheets" },
    ],
    tools: ["Gmail", "GPT agent", "Shopify", "Sheets", "Twilio"],
    savings: "seo.ecommerceCustomerSupportInboxTriage.savings",
  },
  {
    slug: "home-services-quote-follow-up-and-review-requests",
    vertical: "seo.homeServicesQuoteFollowUpAndReviewRequests.vertical",
    workflow: "seo.homeServicesQuoteFollowUpAndReviewRequests.workflow",
    h1: "seo.homeServicesQuoteFollowUpAndReviewRequests.h1",
    metaTitle: "seo.homeServicesQuoteFollowUpAndReviewRequests.metaTitle",
    metaDescription: "seo.homeServicesQuoteFollowUpAndReviewRequests.metaDescription",
    problem: "seo.homeServicesQuoteFollowUpAndReviewRequests.problem",
    solution: "seo.homeServicesQuoteFollowUpAndReviewRequests.solution",
    steps: [
      { label: "seo.homeServicesQuoteFollowUpAndReviewRequests.step1", tool: "Sheets" },
      { label: "seo.homeServicesQuoteFollowUpAndReviewRequests.step2", tool: "GPT agent" },
      { label: "seo.homeServicesQuoteFollowUpAndReviewRequests.step3", tool: "Calendly" },
      { label: "seo.homeServicesQuoteFollowUpAndReviewRequests.step4", tool: "Twilio" },
    ],
    tools: ["GPT agent", "Twilio", "Calendly", "Gmail", "Google Reviews"],
    savings: "seo.homeServicesQuoteFollowUpAndReviewRequests.savings",
  },
  {
    slug: "ai-voice-receptionist-for-dental-practices",
    vertical: "seo.aiVoiceReceptionistForDentalPractices.vertical",
    workflow: "seo.aiVoiceReceptionistForDentalPractices.workflow",
    h1: "seo.aiVoiceReceptionistForDentalPractices.h1",
    metaTitle: "seo.aiVoiceReceptionistForDentalPractices.metaTitle",
    metaDescription: "seo.aiVoiceReceptionistForDentalPractices.metaDescription",
    problem: "seo.aiVoiceReceptionistForDentalPractices.problem",
    solution: "seo.aiVoiceReceptionistForDentalPractices.solution",
    steps: [
      { label: "seo.aiVoiceReceptionistForDentalPractices.step1", tool: "Twilio" },
      { label: "seo.aiVoiceReceptionistForDentalPractices.step2", tool: "GPT voice agent" },
      { label: "seo.aiVoiceReceptionistForDentalPractices.step3", tool: "Calendly" },
      { label: "seo.aiVoiceReceptionistForDentalPractices.step4", tool: "SMS" },
    ],
    tools: ["Twilio", "GPT voice agent", "Calendly", "SMS", "Sheets"],
    savings: "seo.aiVoiceReceptionistForDentalPractices.savings",
  },
  {
    slug: "ai-phone-agent-for-home-services",
    vertical: "seo.aiPhoneAgentForHomeServices.vertical",
    workflow: "seo.aiPhoneAgentForHomeServices.workflow",
    h1: "seo.aiPhoneAgentForHomeServices.h1",
    metaTitle: "seo.aiPhoneAgentForHomeServices.metaTitle",
    metaDescription: "seo.aiPhoneAgentForHomeServices.metaDescription",
    problem: "seo.aiPhoneAgentForHomeServices.problem",
    solution: "seo.aiPhoneAgentForHomeServices.solution",
    steps: [
      { label: "seo.aiPhoneAgentForHomeServices.step1", tool: "Twilio" },
      { label: "seo.aiPhoneAgentForHomeServices.step2", tool: "GPT agent" },
      { label: "seo.aiPhoneAgentForHomeServices.step3", tool: "Housecall Pro" },
      { label: "seo.aiPhoneAgentForHomeServices.step4", tool: "SMS" },
    ],
    tools: ["Twilio", "GPT agent", "Housecall Pro", "Jobber", "SMS"],
    savings: "seo.aiPhoneAgentForHomeServices.savings",
  },
  {
    slug: "ai-voice-agent-for-law-firms",
    vertical: "seo.aiVoiceAgentForLawFirms.vertical",
    workflow: "seo.aiVoiceAgentForLawFirms.workflow",
    h1: "seo.aiVoiceAgentForLawFirms.h1",
    metaTitle: "seo.aiVoiceAgentForLawFirms.metaTitle",
    metaDescription: "seo.aiVoiceAgentForLawFirms.metaDescription",
    problem: "seo.aiVoiceAgentForLawFirms.problem",
    solution: "seo.aiVoiceAgentForLawFirms.solution",
    steps: [
      { label: "seo.aiVoiceAgentForLawFirms.step1", tool: "Twilio" },
      { label: "seo.aiVoiceAgentForLawFirms.step2", tool: "GPT agent" },
      { label: "seo.aiVoiceAgentForLawFirms.step3", tool: "Calendly" },
      { label: "seo.aiVoiceAgentForLawFirms.step4", tool: "Clio" },
    ],
    tools: ["Twilio", "GPT agent", "Clio", "Calendly"],
    savings: "seo.aiVoiceAgentForLawFirms.savings",
  },
  {
    slug: "whatsapp-booking-agent-for-restaurants",
    vertical: "seo.whatsappBookingAgentForRestaurants.vertical",
    workflow: "seo.whatsappBookingAgentForRestaurants.workflow",
    h1: "seo.whatsappBookingAgentForRestaurants.h1",
    metaTitle: "seo.whatsappBookingAgentForRestaurants.metaTitle",
    metaDescription: "seo.whatsappBookingAgentForRestaurants.metaDescription",
    problem: "seo.whatsappBookingAgentForRestaurants.problem",
    solution: "seo.whatsappBookingAgentForRestaurants.solution",
    steps: [
      { label: "seo.whatsappBookingAgentForRestaurants.step1", tool: "WhatsApp Business API" },
      { label: "seo.whatsappBookingAgentForRestaurants.step2", tool: "GPT agent" },
      { label: "seo.whatsappBookingAgentForRestaurants.step3", tool: "OpenTable" },
      { label: "seo.whatsappBookingAgentForRestaurants.step4", tool: "Sheets" },
    ],
    tools: ["WhatsApp Business API", "GPT agent", "OpenTable", "Sheets"],
    savings: "seo.whatsappBookingAgentForRestaurants.savings",
  },
  {
    slug: "whatsapp-sales-agent-for-ecommerce",
    vertical: "seo.whatsappSalesAgentForEcommerce.vertical",
    workflow: "seo.whatsappSalesAgentForEcommerce.workflow",
    h1: "seo.whatsappSalesAgentForEcommerce.h1",
    metaTitle: "seo.whatsappSalesAgentForEcommerce.metaTitle",
    metaDescription: "seo.whatsappSalesAgentForEcommerce.metaDescription",
    problem: "seo.whatsappSalesAgentForEcommerce.problem",
    solution: "seo.whatsappSalesAgentForEcommerce.solution",
    steps: [
      { label: "seo.whatsappSalesAgentForEcommerce.step1", tool: "WhatsApp Business API" },
      { label: "seo.whatsappSalesAgentForEcommerce.step2", tool: "Shopify" },
      { label: "seo.whatsappSalesAgentForEcommerce.step3", tool: "GPT agent" },
      { label: "seo.whatsappSalesAgentForEcommerce.step4", tool: "WhatsApp Business API" },
    ],
    tools: ["WhatsApp Business API", "Shopify", "GPT agent"],
    savings: "seo.whatsappSalesAgentForEcommerce.savings",
  },
  {
    slug: "ai-sales-follow-up-for-b2b-agencies",
    vertical: "seo.aiSalesFollowUpForB2bAgencies.vertical",
    workflow: "seo.aiSalesFollowUpForB2bAgencies.workflow",
    h1: "seo.aiSalesFollowUpForB2bAgencies.h1",
    metaTitle: "seo.aiSalesFollowUpForB2bAgencies.metaTitle",
    metaDescription: "seo.aiSalesFollowUpForB2bAgencies.metaDescription",
    problem: "seo.aiSalesFollowUpForB2bAgencies.problem",
    solution: "seo.aiSalesFollowUpForB2bAgencies.solution",
    steps: [
      { label: "seo.aiSalesFollowUpForB2bAgencies.step1", tool: "HubSpot" },
      { label: "seo.aiSalesFollowUpForB2bAgencies.step2", tool: "GPT agent" },
      { label: "seo.aiSalesFollowUpForB2bAgencies.step3", tool: "Gmail" },
      { label: "seo.aiSalesFollowUpForB2bAgencies.step4", tool: "Calendly" },
    ],
    tools: ["HubSpot", "GPT agent", "Calendly", "Gmail"],
    savings: "seo.aiSalesFollowUpForB2bAgencies.savings",
  },
  {
    slug: "finance-automation-for-agencies",
    vertical: "seo.financeAutomationForAgencies.vertical",
    workflow: "seo.financeAutomationForAgencies.workflow",
    h1: "seo.financeAutomationForAgencies.h1",
    metaTitle: "seo.financeAutomationForAgencies.metaTitle",
    metaDescription: "seo.financeAutomationForAgencies.metaDescription",
    problem: "seo.financeAutomationForAgencies.problem",
    solution: "seo.financeAutomationForAgencies.solution",
    steps: [
      { label: "seo.financeAutomationForAgencies.step1", tool: "GPT agent" },
      { label: "seo.financeAutomationForAgencies.step2", tool: "QuickBooks" },
      { label: "seo.financeAutomationForAgencies.step3", tool: "Stripe" },
      { label: "seo.financeAutomationForAgencies.step4", tool: "Sheets" },
    ],
    tools: ["Stripe", "QuickBooks", "Xero", "GPT agent", "Sheets"],
    savings: "seo.financeAutomationForAgencies.savings",
  },
  {
    slug: "review-management-for-local-services",
    vertical: "seo.reviewManagementForLocalServices.vertical",
    workflow: "seo.reviewManagementForLocalServices.workflow",
    h1: "seo.reviewManagementForLocalServices.h1",
    metaTitle: "seo.reviewManagementForLocalServices.metaTitle",
    metaDescription: "seo.reviewManagementForLocalServices.metaDescription",
    problem: "seo.reviewManagementForLocalServices.problem",
    solution: "seo.reviewManagementForLocalServices.solution",
    steps: [
      { label: "seo.reviewManagementForLocalServices.step1", tool: "GPT agent" },
      { label: "seo.reviewManagementForLocalServices.step2", tool: "Twilio SMS" },
      { label: "seo.reviewManagementForLocalServices.step3", tool: "Google Business Profile" },
      { label: "seo.reviewManagementForLocalServices.step4", tool: "GPT agent" },
    ],
    tools: ["Google Business Profile", "GPT agent", "Twilio SMS"],
    savings: "seo.reviewManagementForLocalServices.savings",
  },
  {
    slug: "med-spa-booking-and-rebooking-agent",
    vertical: "seo.medSpaBookingAndRebookingAgent.vertical",
    workflow: "seo.medSpaBookingAndRebookingAgent.workflow",
    h1: "seo.medSpaBookingAndRebookingAgent.h1",
    metaTitle: "seo.medSpaBookingAndRebookingAgent.metaTitle",
    metaDescription: "seo.medSpaBookingAndRebookingAgent.metaDescription",
    problem: "seo.medSpaBookingAndRebookingAgent.problem",
    solution: "seo.medSpaBookingAndRebookingAgent.solution",
    steps: [
      { label: "seo.medSpaBookingAndRebookingAgent.step1", tool: "GPT agent" },
      { label: "seo.medSpaBookingAndRebookingAgent.step2", tool: "seo.medSpaBookingAndRebookingAgent.toolBookingPms" },
      { label: "seo.medSpaBookingAndRebookingAgent.step3", tool: "SMS/WhatsApp" },
      { label: "seo.medSpaBookingAndRebookingAgent.step4", tool: "Twilio" },
    ],
    tools: ["Twilio", "GPT agent", "seo.medSpaBookingAndRebookingAgent.toolBookingPms", "SMS/WhatsApp"],
    savings: "seo.medSpaBookingAndRebookingAgent.savings",
  },
  {
    slug: "veterinary-appointment-reminders-and-recalls",
    vertical: "seo.veterinaryAppointmentRemindersAndRecalls.vertical",
    workflow: "seo.veterinaryAppointmentRemindersAndRecalls.workflow",
    h1: "seo.veterinaryAppointmentRemindersAndRecalls.h1",
    metaTitle: "seo.veterinaryAppointmentRemindersAndRecalls.metaTitle",
    metaDescription: "seo.veterinaryAppointmentRemindersAndRecalls.metaDescription",
    problem: "seo.veterinaryAppointmentRemindersAndRecalls.problem",
    solution: "seo.veterinaryAppointmentRemindersAndRecalls.solution",
    steps: [
      { label: "seo.veterinaryAppointmentRemindersAndRecalls.step1", tool: "seo.veterinaryAppointmentRemindersAndRecalls.toolPracticeManagement" },
      { label: "seo.veterinaryAppointmentRemindersAndRecalls.step2", tool: "SMS" },
      { label: "seo.veterinaryAppointmentRemindersAndRecalls.step3", tool: "GPT agent" },
      { label: "seo.veterinaryAppointmentRemindersAndRecalls.step4", tool: "Calendly" },
    ],
    tools: ["seo.veterinaryAppointmentRemindersAndRecalls.toolPracticeManagement", "GPT agent", "SMS", "Calendly"],
    savings: "seo.veterinaryAppointmentRemindersAndRecalls.savings",
  },
  {
    slug: "auto-repair-service-scheduling-and-reviews",
    vertical: "seo.autoRepairServiceSchedulingAndReviews.vertical",
    workflow: "seo.autoRepairServiceSchedulingAndReviews.workflow",
    h1: "seo.autoRepairServiceSchedulingAndReviews.h1",
    metaTitle: "seo.autoRepairServiceSchedulingAndReviews.metaTitle",
    metaDescription: "seo.autoRepairServiceSchedulingAndReviews.metaDescription",
    problem: "seo.autoRepairServiceSchedulingAndReviews.problem",
    solution: "seo.autoRepairServiceSchedulingAndReviews.solution",
    steps: [
      { label: "seo.autoRepairServiceSchedulingAndReviews.step1", tool: "Twilio" },
      { label: "seo.autoRepairServiceSchedulingAndReviews.step2", tool: "seo.autoRepairServiceSchedulingAndReviews.toolShopManagementDms" },
      { label: "seo.autoRepairServiceSchedulingAndReviews.step3", tool: "GPT agent" },
      { label: "seo.autoRepairServiceSchedulingAndReviews.step4", tool: "Google Business Profile" },
    ],
    tools: ["Twilio", "GPT agent", "seo.autoRepairServiceSchedulingAndReviews.toolShopManagementDms", "Google Business Profile"],
    savings: "seo.autoRepairServiceSchedulingAndReviews.savings",
  },
  {
    slug: "insurance-agency-lead-qualification-and-renewals",
    vertical: "seo.insuranceAgencyLeadQualificationAndRenewals.vertical",
    workflow: "seo.insuranceAgencyLeadQualificationAndRenewals.workflow",
    h1: "seo.insuranceAgencyLeadQualificationAndRenewals.h1",
    metaTitle: "seo.insuranceAgencyLeadQualificationAndRenewals.metaTitle",
    metaDescription: "seo.insuranceAgencyLeadQualificationAndRenewals.metaDescription",
    problem: "seo.insuranceAgencyLeadQualificationAndRenewals.problem",
    solution: "seo.insuranceAgencyLeadQualificationAndRenewals.solution",
    steps: [
      { label: "seo.insuranceAgencyLeadQualificationAndRenewals.step1", tool: "GPT agent" },
      { label: "seo.insuranceAgencyLeadQualificationAndRenewals.step2", tool: "HubSpot/AMS" },
      { label: "seo.insuranceAgencyLeadQualificationAndRenewals.step3", tool: "Gmail" },
      { label: "seo.insuranceAgencyLeadQualificationAndRenewals.step4", tool: "seo.insuranceAgencyLeadQualificationAndRenewals.toolESign" },
    ],
    tools: ["HubSpot/AMS", "GPT agent", "Gmail", "seo.insuranceAgencyLeadQualificationAndRenewals.toolESign"],
    savings: "seo.insuranceAgencyLeadQualificationAndRenewals.savings",
  },
  {
    slug: "property-management-maintenance-and-tenant-comms",
    vertical: "seo.propertyManagementMaintenanceAndTenantComms.vertical",
    workflow: "seo.propertyManagementMaintenanceAndTenantComms.workflow",
    h1: "seo.propertyManagementMaintenanceAndTenantComms.h1",
    metaTitle: "seo.propertyManagementMaintenanceAndTenantComms.metaTitle",
    metaDescription: "seo.propertyManagementMaintenanceAndTenantComms.metaDescription",
    problem: "seo.propertyManagementMaintenanceAndTenantComms.problem",
    solution: "seo.propertyManagementMaintenanceAndTenantComms.solution",
    steps: [
      { label: "seo.propertyManagementMaintenanceAndTenantComms.step1", tool: "SMS/WhatsApp" },
      { label: "seo.propertyManagementMaintenanceAndTenantComms.step2", tool: "GPT agent" },
      { label: "seo.propertyManagementMaintenanceAndTenantComms.step3", tool: "seo.propertyManagementMaintenanceAndTenantComms.toolPropertyManagementSoftware" },
      { label: "seo.propertyManagementMaintenanceAndTenantComms.step4", tool: "Sheets" },
    ],
    tools: ["seo.propertyManagementMaintenanceAndTenantComms.toolPropertyManagementSoftware", "GPT agent", "SMS/WhatsApp", "Sheets"],
    savings: "seo.propertyManagementMaintenanceAndTenantComms.savings",
  },
];
