import type { LucideIcon } from "lucide-react";
import {
  Baby,
  BedDouble,
  Calculator,
  Camera,
  Hammer,
  HeartHandshake,
  Scissors,
  SprayCan,
  Bot,
  Building2,
  Car,
  Dumbbell,
  HeartPulse,
  MessageCircle,
  PawPrint,
  Phone,
  Receipt,
  Scale,
  ShoppingBag,
  Star,
  Stethoscope,
  TrendingUp,
  Umbrella,
  Utensils,
  Wrench,
} from "lucide-react";

export type Bundle = {
  name: string;
  slug: string; // → /automations/{slug}
  icon: LucideIcon;
  tagline: string;
  includes: string[];
  savings: string; // display, e.g. "~$3,400/mo"
  basePrice: number; // monthly retainer for the base OS
  baseSavings: number; // typical monthly savings
  vertical: string; // for getBenchmark()
};

export const bundles: Bundle[] = [
  {
    name: "sol.bundleRestaurantName",
    slug: "restaurant-reservation-and-review-agent",
    icon: Utensils,
    tagline: "sol.bundleRestaurantTagline",
    includes: ["sol.incReservationReviewAgent", "sol.incWhatsappBookingAgent", "sol.incInboxDmTriage", "sol.incNoShowReminders"],
    savings: "sol.savings3400",
    basePrice: 1800,
    baseSavings: 3400,
    vertical: "Restaurant",
  },
  {
    name: "sol.bundleHomeServicesName",
    slug: "ai-phone-agent-for-home-services",
    icon: Wrench,
    tagline: "sol.bundleHomeServicesTagline",
    includes: ["sol.incAiPhoneAnsweringAgent", "sol.incMissedCallBookedJob", "sol.incQuoteFollowup", "sol.incReviewRequests"],
    savings: "sol.savings4800",
    basePrice: 2200,
    baseSavings: 4800,
    vertical: "Home services",
  },
  {
    name: "sol.bundleDentalName",
    slug: "ai-voice-receptionist-for-dental-practices",
    icon: Stethoscope,
    tagline: "sol.bundleDentalTagline",
    includes: ["sol.incAiVoiceReceptionist", "sol.incAppointmentReminders", "sol.incRebookingRecalls", "sol.incIntakeAutomation"],
    savings: "sol.savings5200",
    basePrice: 2600,
    baseSavings: 5200,
    vertical: "Dental",
  },
  {
    name: "sol.bundleRealEstateName",
    slug: "real-estate-lead-qualification-and-follow-up",
    icon: Building2,
    tagline: "sol.bundleRealEstateTagline",
    includes: ["sol.incLeadQualAgent", "sol.incMultiTouchFollowup", "sol.incWhatsappSmsAgent", "sol.incShowingScheduler"],
    savings: "sol.savings5600",
    basePrice: 2400,
    baseSavings: 5600,
    vertical: "Real estate",
  },
  {
    name: "sol.bundleLawFirmName",
    slug: "ai-voice-agent-for-law-firms",
    icon: Scale,
    tagline: "sol.bundleLawFirmTagline",
    includes: ["sol.incAiIntakeCallAgent", "sol.incConflictIntakeQuestions", "sol.incDocCollection", "sol.incConsultScheduling"],
    savings: "sol.savings4200",
    basePrice: 2200,
    baseSavings: 4200,
    vertical: "Law firm",
  },
  {
    name: "sol.bundleEcommerceName",
    slug: "shopify-store-abandoned-cart-recovery",
    icon: ShoppingBag,
    tagline: "sol.bundleEcommerceTagline",
    includes: ["sol.incAbandonedCartRecovery", "sol.incWhatsappSalesSupport", "sol.incSupportInboxTriage", "sol.incReviewEngine"],
    savings: "sol.savings7200",
    basePrice: 2800,
    baseSavings: 7200,
    vertical: "E-commerce",
  },
  {
    name: "sol.bundleMedSpaName",
    slug: "med-spa-booking-and-rebooking-agent",
    icon: HeartPulse,
    tagline: "sol.bundleMedSpaTagline",
    includes: ["sol.incBookingConsultAgent", "sol.incCancellationFillWaitlist", "sol.incRebookingRecalls", "sol.incReviewRequests"],
    savings: "sol.savings5000",
    basePrice: 2400,
    baseSavings: 5000,
    vertical: "Med spa",
  },
  {
    name: "sol.bundleVeterinaryName",
    slug: "veterinary-appointment-reminders-and-recalls",
    icon: PawPrint,
    tagline: "sol.bundleVeterinaryTagline",
    includes: ["sol.incAppointmentReminders", "sol.incVaccineWellnessRecalls", "sol.incAfterHoursTriage", "sol.incReviewRequests"],
    savings: "sol.savings4400",
    basePrice: 2200,
    baseSavings: 4400,
    vertical: "Veterinary",
  },
  {
    name: "sol.bundleFitnessName",
    slug: "gym-fitness-membership-onboarding-and-winback",
    icon: Dumbbell,
    tagline: "sol.bundleFitnessTagline",
    includes: ["sol.incTrialToMemberNurture", "sol.incClassBookingAgent", "sol.incNoShowWinback", "sol.incMembershipOnboarding"],
    savings: "sol.savings3600",
    basePrice: 1800,
    baseSavings: 3600,
    vertical: "Fitness",
  },
  {
    name: "sol.bundleAutoName",
    slug: "auto-repair-service-scheduling-and-reviews",
    icon: Car,
    tagline: "sol.bundleAutoTagline",
    includes: ["sol.incServiceSchedulingAgent", "sol.incMissedCallRecovery", "sol.incQuoteStatusFollowup", "sol.incReviewEngine"],
    savings: "sol.savings6000",
    basePrice: 2600,
    baseSavings: 6000,
    vertical: "Auto repair",
  },
  {
    name: "sol.bundleInsuranceName",
    slug: "insurance-agency-lead-qualification-and-renewals",
    icon: Umbrella,
    tagline: "sol.bundleInsuranceTagline",
    includes: ["sol.incLeadQualAgent", "sol.incRenewalChasing", "sol.incDocCollection", "sol.incMeetingScheduler"],
    savings: "sol.savings6500",
    basePrice: 2600,
    baseSavings: 6500,
    vertical: "Insurance",
  },
  {
    name: "sol.bundlePropertyName",
    slug: "property-management-maintenance-and-tenant-comms",
    icon: Building2,
    tagline: "sol.bundlePropertyTagline",
    includes: ["sol.incMaintenanceTriageAgent", "sol.incTenantQaRentReminders", "sol.incLeadToLeaseFollowup", "sol.incReviewRequests"],
    savings: "sol.savings4600",
    basePrice: 2200,
    baseSavings: 4600,
    vertical: "Property management",
  },
  // ── New underserved verticals (July 2026 pain research) ──
  {
    name: "sol.bundleSalonName",
    slug: "salon-rebooking-and-no-show-agent",
    icon: Scissors,
    tagline: "sol.bundleSalonTagline",
    includes: ["sol.incSalon1", "sol.incSalon2", "sol.incSalon3", "sol.incSalon4"],
    savings: "sol.bundleSalonSavings",
    basePrice: 1500,
    baseSavings: 2800,
    vertical: "Salon",
  },
  {
    name: "sol.bundleAccountingName",
    slug: "accounting-firm-client-document-chaser",
    icon: Calculator,
    tagline: "sol.bundleAccountingTagline",
    includes: ["sol.incAccounting1", "sol.incAccounting2", "sol.incAccounting3", "sol.incAccounting4"],
    savings: "sol.bundleAccountingSavings",
    basePrice: 2400,
    baseSavings: 5400,
    vertical: "Accounting",
  },
  {
    name: "sol.bundleContractorName",
    slug: "contractor-estimate-follow-up-agent",
    icon: Hammer,
    tagline: "sol.bundleContractorTagline",
    includes: ["sol.incContractor1", "sol.incContractor2", "sol.incContractor3", "sol.incContractor4"],
    savings: "sol.bundleContractorSavings",
    basePrice: 2600,
    baseSavings: 7500,
    vertical: "Contractor",
  },
  {
    name: "sol.bundleCleaningName",
    slug: "cleaning-service-quote-and-winback-agent",
    icon: SprayCan,
    tagline: "sol.bundleCleaningTagline",
    includes: ["sol.incCleaning1", "sol.incCleaning2", "sol.incCleaning3", "sol.incCleaning4"],
    savings: "sol.bundleCleaningSavings",
    basePrice: 1600,
    baseSavings: 3100,
    vertical: "Cleaning",
  },
  {
    name: "sol.bundleChildcareName",
    slug: "childcare-enrollment-and-parent-comms-agent",
    icon: Baby,
    tagline: "sol.bundleChildcareTagline",
    includes: ["sol.incChildcare1", "sol.incChildcare2", "sol.incChildcare3", "sol.incChildcare4"],
    savings: "sol.bundleChildcareSavings",
    basePrice: 1800,
    baseSavings: 3600,
    vertical: "Childcare",
  },
  {
    name: "sol.bundleStrName",
    slug: "short-term-rental-guest-messaging-agent",
    icon: BedDouble,
    tagline: "sol.bundleStrTagline",
    includes: ["sol.incStr1", "sol.incStr2", "sol.incStr3", "sol.incStr4"],
    savings: "sol.bundleStrSavings",
    basePrice: 1400,
    baseSavings: 2600,
    vertical: "Short-term rental",
  },
  {
    name: "sol.bundleNonprofitName",
    slug: "nonprofit-donor-retention-agent",
    icon: HeartHandshake,
    tagline: "sol.bundleNonprofitTagline",
    includes: ["sol.incNonprofit1", "sol.incNonprofit2", "sol.incNonprofit3", "sol.incNonprofit4"],
    savings: "sol.bundleNonprofitSavings",
    basePrice: 1200,
    baseSavings: 2400,
    vertical: "Nonprofit",
  },
  {
    name: "sol.bundlePhotographerName",
    slug: "photographer-lead-and-booking-agent",
    icon: Camera,
    tagline: "sol.bundlePhotographerTagline",
    includes: ["sol.incPhotographer1", "sol.incPhotographer2", "sol.incPhotographer3", "sol.incPhotographer4"],
    savings: "sol.bundlePhotographerSavings",
    basePrice: 1100,
    baseSavings: 2300,
    vertical: "Photography",
  },
];

export type Addon = {
  id: string;
  name: string;
  icon: LucideIcon;
  price: number;
  savings: number;
  desc: string;
};

/** A la carte agents that attach to any OS — the configurable moat. */
export const addons: Addon[] = [
  { id: "voice", name: "sol.addonVoiceName", icon: Phone, price: 800, savings: 3000, desc: "sol.addonVoiceDesc" },
  { id: "whatsapp", name: "sol.addonWhatsappName", icon: MessageCircle, price: 600, savings: 2400, desc: "sol.addonWhatsappDesc" },
  { id: "reviews", name: "sol.addonReviewsName", icon: Star, price: 400, savings: 1200, desc: "sol.addonReviewsDesc" },
  { id: "sdr", name: "sol.addonSdrName", icon: TrendingUp, price: 700, savings: 3500, desc: "sol.addonSdrDesc" },
  { id: "finance", name: "sol.addonFinanceName", icon: Receipt, price: 600, savings: 2000, desc: "sol.addonFinanceDesc" },
  { id: "custom", name: "sol.addonCustomName", icon: Bot, price: 500, savings: 1500, desc: "sol.addonCustomDesc" },
];
